// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.SalesManagementService.#FindOrdersByDates(System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.SalesManagementService.#FindOrdersByOrderInformation(System.Int32,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.SalesManagementService.#FindOrdersByShippingData(System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.SalesManagementService.#FindPagedOrders(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.SalesManagementService.#FindPagedProducts(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.SalesManagementService.#FindProductBySpecification(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.ISalesManagementService.#FindOrdersByDates(System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.ISalesManagementService.#FindOrdersByOrderInformation(System.Int32,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.ISalesManagementService.#FindOrdersByShippingData(System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.ISalesManagementService.#FindPagedOrders(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.ISalesManagementService.#FindPagedProducts(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.SalesManagement.ISalesManagementService.#FindProductBySpecification(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.CustomersManagement.ICustomerManagementService.#FindCountriesByName(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.CustomersManagement.ICustomerManagementService.#FindPagedCountries(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.CustomersManagement.ICustomerManagementService.#FindPagedCustomers(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.IBankingManagementService.#FindBankAccounts(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.IBankingManagementService.#FindBankTransfers(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.IBankingManagementService.#FindPagedBankAccounts(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.CustomersManagement.CustomerManagementService.#FindCountriesByName(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.CustomersManagement.CustomerManagementService.#FindPagedCountries(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.CustomersManagement.CustomerManagementService.#FindPagedCustomers(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "type", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.BankingManagementService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1816:CallGCSuppressFinalizeCorrectly", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.BankingManagementService.#Dispose()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.BankingManagementService.#Dispose()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.BankingManagementService.#FindBankTransfers(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.BankingManagementService.#FindPagedBankAccounts(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Samples.NLayerApp.Application.MainModule.BankingManagement.BankingManagementService.#FindBankAccounts(System.String,System.String)")]
