ALTER TABLE [dbo].[OrderDetails]
    ADD CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

